### ISSUE TITLE
RPM post install, hoot-services.war files not always available to edit

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#30]
The RPM post install hook that updates hoot-services config files with a generated password sometimes fails because the war file hasn't been exploded by tomcat at the time the post install hook runs.

```
==> default: sed: can't read /var/lib/tomcat6/webapps/hoot-services/WEB-INF/classes/db/liquibase.properties: No such file or directory
==> default: sed: can't read /var/lib/tomcat6/webapps/hoot-services/WEB-INF/classes/db/spring-database.xml: No such file or directory
````

This leads to the hoot schema not being created because the liquibase command fails.
```
==> default: Liquibase update Failed: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "hoot"
==> default: SEVERE 3/15/16 11:37 PM:liquibase: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "hoot"
==> default: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "hoot"
==> default:    at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(Unknown Source)
==> default:    at liquibase.integration.commandline.Main.doMigration(Unknown Source)
==> default:    at liquibase.integration.commandline.Main.main(Unknown Source)
==> default: Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "hoot"
==> default:    at liquibase.database.DatabaseFactory.openConnection(Unknown Source)
==> default:    at liquibase.database.DatabaseFactory.openDatabase(Unknown Source)
==> default:    ... 3 more
==> default: Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "hoot"
==> default:    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293)
==> default:    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
==> default:    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
==> default:    at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
==> default:    at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
==> default:    at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
==> default:    at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
==> default:    at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
==> default:    at org.postgresql.Driver.makeConnection(Driver.java:393)
==> default:    at org.postgresql.Driver.connect(Driver.java:267)
==> default:    ... 5 more
```

**Comment by brianhatchl** [comment]
This is fixed and working now both locally and on jenkins
