### ISSUE TITLE
Liquibase failing during install on EC2

### ISSUE THREAD

**Issue by jasonsurratt** [ngageoint/hootenanny-rpms#49]
I tried the new RPM install on an AWS instance that started with a CentOS 6.5 from the marketplace. 
I added the epel repo and ran yum update which updated me to CentOS 6.7
I then added the hoot repo and ran the hootenanny-autostart install.

Liquibase fails:

```
----------------------------------------------------------------
Liquibase update Failed: Unknown Reason
SEVERE 4/5/16 8:09 PM:liquibase: Unknown Reason
java.lang.ExceptionInInitializerError
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at liquibase.sqlgenerator.SqlGeneratorFactory.<init>(Unknown Source)
at liquibase.sqlgenerator.SqlGeneratorFactory.getInstance(Unknown Source)
at liquibase.executor.AbstractExecutor.applyVisitors(Unknown Source)
at liquibase.executor.jvm.JdbcExecutor.access$500(Unknown Source)
at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(Unknown Source)
at liquibase.executor.jvm.JdbcExecutor.execute(Unknown Source)
at liquibase.executor.jvm.JdbcExecutor.execute(Unknown Source)
at liquibase.executor.jvm.JdbcExecutor.execute(Unknown Source)
at liquibase.lockservice.StandardLockService.init(Unknown Source)
at liquibase.lockservice.StandardLockService.acquireLock(Unknown Source)
at liquibase.lockservice.StandardLockService.waitForLock(Unknown Source)
at liquibase.Liquibase.update(Unknown Source)
at liquibase.Liquibase.update(Unknown Source)
at liquibase.integration.commandline.Main.doMigration(Unknown Source)
at liquibase.integration.commandline.Main.main(Unknown Source)
Caused by: liquibase.exception.UnexpectedLiquibaseException: java.net.UnknownHostException: ip-172-16-63-44: ip-172-16-63-44: unknown error
at liquibase.sqlgenerator.core.LockDatabaseChangeLogGenerator.<clinit>(Unknown Source)
... 19 more
Caused by: java.net.UnknownHostException: ip-172-16-63-44: ip-172-16-63-44: unknown error
at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
at liquibase.util.NetUtil.getLocalHostName(Unknown Source)
... 20 more
Caused by: java.net.UnknownHostException: ip-172-16-63-44: unknown error
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
... 21 more
```

For more information, use the --logLevel flag
----------------------------------------------------------------

Liquibase does not know how to resolve the hostname that EC2 assigns the instance which is always based on the VPC IP address assigned to the instance.
Adding that hostname to the /etc/hosts file resolves the issue, if done before running "sudo yum install hootenanny-autostart". I suppose Liquibase is not using localhost in a way we would expect.

**Comment by jasonsurratt** [comment]
@brianhatchl @qwyjibojones FYI

**Comment by brianhatchl** [comment]
I hope to have addressed this issue in this commit https://github.com/ngageoint/hootenanny-rpms/pull/48/commits/f7b83bccc140c0f87083c0a589d87a545e672cc7 that's now been merged into develop by adding a host and port params to the liquibase command that are sourced from conf/DatabaseConfig.sh.

**Comment by brianhatchl** [comment]
@qwyjibojones Ready for test on a fresh CentOS instance.  We want to make sure it works without any fiddling.

**Comment by brianhatchl** [comment]
@qwyjibojones were you able to test these fixes installing hoot rpms on the aws centos instance?

**Comment by qwyjibojones** [comment]
Testing with a unmodified AWS instance still has issues.
I tried adding the "ip-xxx.xxx.xxx" AWS generated hostname as an alias to the localhost line in /etc/hosts.
------------
[hoottest@ip-172-16-186-161 ~]$ cat /etc/hosts
127.0.0.1		localhost.localdomain localhost ip-172-16-186-161
::1		localhost6.localdomain6 localhost6
-------------
Liquibase still errors out on the install.


Adding a separate line to /etc/hosts for the ip and hostname assigned by AWS, prior to installing hoot allowed Liquibase to complete this time.

[hoottest@ip-172-16-186-161 ~]$ cat /etc/hosts
127.0.0.1		localhost.localdomain localhost
::1		localhost6.localdomain6 localhost6

172.16.186.161  ip-172-16-186-161

**Comment by gschmidtee** [comment]
Notes from c2s:
- ran into similar issue with nominatim install when it tried to reach the DB.
- adding the <ip_addr> ip_name could work but temporarily.  When you shutdown the machine and restart you get a new external  ip
- to save on configuration, ending up leaving the connection to the DB set to ami default 127.0.0.1
- Don't know if that will help with Liquibase, but put it out there for you
- Other question is liquibase still necessary?  alternatively you could probably do something similar to what I did with the api db setup for hoot, use the psql ingest approach to create the DB.  Unless you are using liquibase for some other stuff?
